dist: xenial

language: node_js

node_js:
  - "lts/*"

cache:
  yarn: true

services:
  - xvfb

script:
  - yarn lint
  - yarn flow
  - yarn test --coverage
  - yarn build:prod
  - yarn build:dist --publish "never"
  - NODE_ENV=production yarn sequelize db:migrate
  - yarn test-e2e
  - yarn codecov

branches:
  except:
  - experimental